import json
import math
import re
from typing import List, Dict, Any, Optional

# =====================================================================
# 1. TOOL DEFINITIONS & IMPLEMENTATION
# =====================================================================

def compute_emi(amount: float, rate_annual: float, months: int) -> Dict[str, Any]:
    """
    Computes monthly EMI and total interest for a given loan amount, 
    annual interest rate (%), and tenure in months.
    """
    if months <= 0 or amount <= 0:
        return {"error": "Amount and months must be greater than 0."}
    
    r = (rate_annual / 100) / 12  # Monthly interest rate
    
    if r == 0:
        emi = amount / months
        total_payment = amount
        total_interest = 0.0
    else:
        # Standard EMI Formula: P * r * (1+r)^n / ((1+r)^n - 1)
        pow_factor = math.pow(1 + r, months)
        emi = amount * r * pow_factor / (pow_factor - 1)
        total_payment = emi * months
        total_interest = total_payment - amount

    return {
        "amount": round(amount, 2),
        "rate_annual": rate_annual,
        "months": months,
        "emi": round(emi, 2),
        "total_payment": round(total_payment, 2),
        "total_interest": round(total_interest, 2)
    }


def compare_options(options: List[Dict[str, Any]], monthly_income: Optional[float] = None) -> Dict[str, Any]:
    """
    Compares multiple loan EMI options, evaluates total interest differences,
    and identifies which options are affordable based on a 40% income rule.
    """
    if not options:
        return {"error": "No options provided for comparison."}
    
    evaluated = []
    recommended_option = None
    lowest_interest_option = min(options, key=lambda x: x.get("total_interest", float('inf')))

    for opt in options:
        emi = opt.get("emi", 0)
        affordable = True
        affordability_note = "Income not provided."

        if monthly_income and monthly_income > 0:
            # Rule: EMI should ideally be <= 40% of net monthly income
            emi_to_income_ratio = (emi / monthly_income) * 100
            affordable = emi_to_income_ratio <= 40.0
            affordability_note = (
                f"EMI is {round(emi_to_income_ratio, 1)}% of income. "
                + ("Affordable (<=40%)." if affordable else "Unaffordable (>40%).")
            )

        evaluated.append({
            "loan_details": opt,
            "affordable": affordable,
            "note": affordability_note
        })

        if affordable and (recommended_option is None or opt["emi"] < recommended_option["emi"]):
            recommended_option = opt

    return {
        "compared_options": evaluated,
        "lowest_interest_option": lowest_interest_option,
        "recommended_option": recommended_option if recommended_option else "None fit the 40% affordability threshold."
    }


# Tool Declarations Schema (for LLM tool-calling engines)
TOOLS_SCHEMA = [
    {
        "name": "compute_emi",
        "description": "Calculate EMI, total interest, and total payment for a specific loan offer.",
        "parameters": {
            "type": "object",
            "properties": {
                "amount": {"type": "number", "description": "Principal loan amount"},
                "rate_annual": {"type": "number", "description": "Annual interest rate percentage (e.g., 8.5)"},
                "months": {"type": "integer", "description": "Loan tenure in months"}
            },
            "required": ["amount", "rate_annual", "months"]
        }
    },
    {
        "name": "compare_options",
        "description": "Compares previously calculated loan options and checks affordability against monthly income.",
        "parameters": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "array",
                    "description": "List of loan option dicts generated by compute_emi",
                    "items": {"type": "object"}
                },
                "monthly_income": {"type": "number", "description": "User's stated monthly income"}
            },
            "required": ["options"]
        }
    }
]

# Knowledge base dictionary for conversational responses
KNOWLEDGE_BASE = {
    "what_is_a_loan": """A **loan** is a sum of money borrowed from a financial institution or individual that is expected to be paid back with interest over a specified period.

**Key Components of a Loan:**
* **Principal:** The actual amount of money borrowed.
* **Interest Rate:** The percentage charged by the lender for borrowing the money.
* **Tenure:** The time duration agreed upon to pay back the loan.
* **EMI (Equated Monthly Installment):** The fixed monthly payment made to repay the loan.""",

    "types_of_loan": """Here are the primary types of loans available:

* **Personal Loan:** An unsecured loan used for personal expenses like emergencies, travel, or weddings.
* **Home Loan:** A secured loan specifically taken to purchase or construct residential property.
* **Auto / Vehicle Loan:** A secured loan used to buy automobiles, where the vehicle acts as collateral.
* **Education Loan:** A loan designed to cover tuition fees and educational expenses for higher studies.
* **Business Loan:** Credit extended to businesses for working capital, expansion, or equipment purchase."""
}

# =====================================================================
# 2. AGENT WITH MEMORY AND PLAN-ACT LOOP
# =====================================================================

class EMILoanAgent:
    def __init__(self, monthly_income: Optional[float] = None):
        self.memory = {
            "monthly_income": monthly_income,
            "computed_options": [],
            "conversation_history": []
        }

    def set_income(self, income: float):
        self.memory["monthly_income"] = income

    def execute_tool(self, tool_name: str, args: Dict[str, Any]) -> Any:
        """Invokes Python functions directly based on Agent Decisions."""
        if tool_name == "compute_emi":
            res = compute_emi(args["amount"], args["rate_annual"], args["months"])
            if "error" not in res:
                if res not in self.memory["computed_options"]:
                    self.memory["computed_options"].append(res)
            return res

        elif tool_name == "compare_options":
            income = args.get("monthly_income", self.memory["monthly_income"])
            options = args.get("options", self.memory["computed_options"])
            return compare_options(options=options, monthly_income=income)

        else:
            return {"error": f"Unknown tool: {tool_name}"}

    def run_step(self, user_prompt: str) -> Dict[str, Any]:
        """
        Hybrid Plan-Act loop: handles conversational/conceptual questions like a chatbot
        and executes mathematical tools for specific calculations/comparisons.
        """
        trace = []
        prompt_lower = user_prompt.lower()
        self.memory["conversation_history"].append({"role": "user", "content": user_prompt})

        loan_terms = ["loan", "emi", "interest", "principal", "borrow", "lender", "tenure", "salary", "income"]
        is_loan_query = any(term in prompt_lower for term in loan_terms)

        # -------------------------------------------------------------
        # STEP 1: CONVERSATIONAL INTENT ROUTING (CHATBOT MODE)
        # -------------------------------------------------------------
        if ("what is" in prompt_lower or "types of" in prompt_lower or "define" in prompt_lower or "explain" in prompt_lower) and is_loan_query:
            trace.append("[Plan Step] Conversational request detected. Generating explanation from Knowledge Base.")
            
            response = ""
            if "what" in prompt_lower and "loan" in prompt_lower:
                response += KNOWLEDGE_BASE["what_is_a_loan"] + "\n\n"
            if "type" in prompt_lower or "different" in prompt_lower:
                response += KNOWLEDGE_BASE["types_of_loan"]

            if not response:
                response = "Loans are financial agreements where a lender provides funds to a borrower, who agrees to repay the principal along with interest over a fixed tenure."

            self.memory["conversation_history"].append({"role": "agent", "content": response})
            return {"trace": trace, "response": response}

        # Handle non-financial queries safely
        elif not is_loan_query and not any(char.isdigit() for char in user_prompt):
            trace.append("[Plan Step] Non-financial query detected. Rejecting gracefully.")
            response = "I am a specialized **EMI and Loan Advisor Agent**. I can help you calculate EMIs, evaluate affordability, or explain loan types. Please ask a loan-related question!"
            self.memory["conversation_history"].append({"role": "agent", "content": response})
            return {"trace": trace, "response": response}

        # -------------------------------------------------------------
        # STEP 2: PARAMETER EXTRACTION (AGENT / TOOL MODE)
        # -------------------------------------------------------------
        # Extract Income if mentioned
        income_match = re.search(r'(?:income|salary|earn)[^0-9]*([0-9]+(?:,[0-9]+)*)', user_prompt, re.IGNORECASE)
        if income_match:
            raw_inc = income_match.group(1).replace(",", "")
            inc = float(raw_inc)
            self.set_income(inc)
            trace.append(f"[Memory Update] Stored monthly income: ₹{inc:,.2f}")

        # Extract Loan Parameters
        amount_match = re.search(r'(?:loan|amount|take)[^0-9]*([0-9]+(?:,[0-9]+)*)', user_prompt, re.IGNORECASE)
        rate_match = re.search(r'([0-9]+(?:\.[0-9]+)?)\s*%', user_prompt)
        months_match = re.search(r'([0-9]+)\s*(?:months|m\b|years|y\b|tenure)', user_prompt, re.IGNORECASE)

        # Path A: Specific Custom Calculation requested
        if amount_match and (rate_match or months_match):
            amt = float(amount_match.group(1).replace(",", ""))
            rate = float(rate_match.group(1)) if rate_match else 8.5
            
            raw_months = int(months_match.group(1)) if months_match else 36
            if months_match and 'year' in months_match.group(0).lower():
                raw_months *= 12

            trace.append(f"[Plan Step] Parameters extracted: Amount=₹{amt:,.2f}, Rate={rate}%, Tenure={raw_months}m")
            
            opt_custom = self.execute_tool("compute_emi", {"amount": amt, "rate_annual": rate, "months": raw_months})
            trace.append(f"[Tool Call] compute_emi({amt}, {rate}%, {raw_months}m) -> EMI: ₹{opt_custom['emi']}")

            comp = self.execute_tool("compare_options", {"monthly_income": self.memory["monthly_income"]})
            trace.append("[Tool Call] compare_options() executed.")

            response = self._format_comparison_response(comp)
            self.memory["conversation_history"].append({"role": "agent", "content": response})
            return {"trace": trace, "response": response}

        # Path B: Follow-up questions on existing stored options
        if ("compare" in prompt_lower or "afford" in prompt_lower or "interest" in prompt_lower) and len(self.memory["computed_options"]) > 0:
            trace.append("[Plan Step] Evaluating stored options against current income.")
            comp_result = self.execute_tool("compare_options", {"monthly_income": self.memory["monthly_income"]})
            trace.append("[Tool Call] compare_options() executed.")

            response = self._format_comparison_response(comp_result)
            self.memory["conversation_history"].append({"role": "agent", "content": response})
            return {"trace": trace, "response": response}

        # Path C: Default Demonstration Setup
        trace.append("[Plan Step] Initializing baseline comparison options.")
        self.memory["computed_options"].clear()

        opt1 = self.execute_tool("compute_emi", {"amount": 500000, "rate_annual": 8.5, "months": 36})
        opt2 = self.execute_tool("compute_emi", {"amount": 500000, "rate_annual": 7.5, "months": 60})

        comp = self.execute_tool("compare_options", {"monthly_income": self.memory["monthly_income"]})
        response = self._format_comparison_response(comp)
        
        self.memory["conversation_history"].append({"role": "agent", "content": response})
        return {"trace": trace, "response": response}

    def _format_comparison_response(self, comp_result: Dict[str, Any]) -> str:
        rec = comp_result.get("recommended_option")
        lowest_int = comp_result.get("lowest_interest_option")
        
        out = "### EMI & Loan Recommendation Summary\n\n"
        out += "| Option | Amount | Tenure | Rate | EMI | Total Interest | Affordability |\n"
        out += "|---|---|---|---|---|---|---|\n"
        
        for item in comp_result["compared_options"]:
            opt = item["loan_details"]
            out += f"| Loan | ₹{opt['amount']} | {opt['months']}m | {opt['rate_annual']}% | ₹{opt['emi']} | ₹{opt['total_interest']} | {item['note']} |\n"
        
        out += "\n**Analysis & Decision:**\n"
        if isinstance(rec, dict):
            out += f"- **Recommended Option:** Loan with EMI of **₹{rec['emi']}** ({rec['months']} months @ {rec['rate_annual']}%).\n"
        else:
            out += f"- **Recommendation:** {rec}\n"
            
        if isinstance(lowest_int, dict):
            out += f"- **Total Interest Leader:** Option with {lowest_int['months']} months tenure saves the most interest (Total Interest: ₹{lowest_int['total_interest']}).\n"

        return out